on:
  - push
  - workflow_dispatch

jobs:
  repro:
    strategy:
      fail-fast: false
      matrix:
        version: [10.0.1, 10.0.2, 10.0.3, 10.0.4]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install .NET Runtime
        run: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --runtime dotnet --version ${{ matrix.version }} --install-dir ./.dotnet
          ./dotnet-install.sh --version 10.0.101 --install-dir ./.dotnet
          echo "./.dotnet" >> $GITHUB_PATH

      - name: .NET Info
        run: |
          which dotnet
          dotnet --info

      - name: Run VB
        run: dotnet run --project VB
